services:
  app:
    image: laravel-dev
    container_name: ${APP_NAME}-app
    env_file:
      - .env
    volumes:
      - ./htdocs:/var/www/html
      - ~/.pi/agent_docker:/root/.pi/agent
    ports:
      - ${APP_PORT_PREFIX:-}80:80
    depends_on:
      - mysql
  mysql:
    image: mariadb
    container_name: ${APP_NAME}-mysql
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - ${APP_PORT_PREFIX:-}82:3306
    cap_add:
      - SYS_NICE
volumes:
  mysql:
    driver: "local"
